# Funciones

Una función es un bloque de código organizado y reutilizable que se utiliza para realizar una única acción relacionada. Las funciones proporcionan una mejor modularidad para su aplicación y un alto grado de reutilización de código.

In [0]:
#Definimos una funcion que calcule la media de una lista de numeros
def media(v):
  media = 0
  for i in v:
    media += i

  return(media/len(v))

In [0]:
#Definamos una funcion para calcular la varianza
def varianza(v):
  var = 0
  m = media(v)
  for i in v:
    var += (i - m)**2

  return(var/len(v))

In [34]:
#Ejecutamos la funciones
lista = [4,2,2,2,2,3,4,5,6]
media(lista), varianza(lista)

(3.3333333333333335, 2.0)

Ejemplos de funciones ya construidas en python

In [36]:
#Forma facil de calcular la media
sum(lista)/len(lista)

3.3333333333333335

In [42]:
#Funcion que calcula el maximo y minimo
max(lista) , min(lista)

(6, 2)

#clases y objetos en python

En python casi todo es un objecto!

Los objetos son un conjunto de atributos (tambien llamados instancias)  y metodos (que son funciones como lo veremos)  asociados a un tipo de dato.

Las clases son los planos "BluePrints" de los objetos

In [0]:
#creacion de la clase robot usando el metodo __init__
class robot():
  def __init__(self, nombre='pepe', color='azul' , edad=100):
    self.nombre = nombre
    self.color = color
    self.edad = edad

  def hablar(self):
    print(f"Hola, mi nombre es {self.nombre} y tengo {self.edad} años" )

In [0]:
#cracion de los objetos  robot_1 y robot_2
robot_1 = robot('Juan', 'rojo', 5); robot_2 = robot()

In [59]:
 # verifiquemos el tipo de robot_1
type(robot_1)

__main__.robot

In [60]:
 #atributos del objeto robot_1
robot_1.nombre, robot_1.color, robot_1.edad

('Juan', 'rojo', 5)

In [61]:
 #atributos del objeto robot_2
robot_2.nombre, robot_2.color, robot_2.edad

('pepe', 'azul', 100)

Hay dos formas de ejecutar los metodos

In [62]:
 #Forma 1
robot_1.hablar()

Hola, mi nombre es Juan y tengo 5 años


In [64]:
 #Forma 2
robot.hablar(robot_1)

Hola, mi nombre es Juan y tengo 5 años


Ejemplos usando metodos ya construidos en python

In [0]:
#creacion de una cadena de caracteres
palabra = 'EsTa eS La claSe #2'

In [67]:
# Palabras en minuscula
palabra.lower() , str.lower(palabra)

('esta es la clase #2', 'esta es la clase #2')

In [0]:
#Palabras en mayusculas
palabra.upper(), str.upper(palabra)

# Librerias en python

Una libreria es una coleccion de clses y metodos los cuales nos permiten crear objetos sin la nececidad de programarlos explicitamente.

Existen muchas librerias, las mas utilizadas por nosostros seran:
* numpy
* pandas 
* matplotlib
* seaborn
* sklearn


#Numpy

Esta libreria proporciona objetos arreglos multidimensionales (tensores) de alto desempeño, ademas de erramientas para trabajar con estos arreglos

In [0]:
#Importar numpy
import numpy as np

## 1D array 

un arreglo unidimensional es una colecion de tipos de datos los cuales se encuntran indexados ( tal y como las listas ). A diferencia de las listas, los arreglos 1D ( y en general los arreglos de cualquier dimension ) solo pueden contener un tipo de dato.

Los arreglos de python soportan indexacion y slicing

para crear un arreglo 1D de python , podemos usar una lista de numpy


In [85]:
v = np.array([1,2,2,5,2.6,5,6,7,3]) #creacion de un arreglo 1D de numpy
print(type(v))
v #Veamos el vector y a que clase pertenece (esto es , veamos que tipo de dato es)

<class 'numpy.ndarray'>


array([1. , 2. , 2. , 5. , 2.6, 5. , 6. , 7. , 3. ])

In [86]:
#indexacion
v[0], v[1] , v[-1] , v[8]

(1.0, 2.0, 3.0, 3.0)

In [95]:
#slicing [indice_inicial:indice_fianl:paso]
v[0:5:2], v[::-1] , v[1::3] , v[5::]

(array([1. , 2. , 2.6]),
 array([3. , 7. , 6. , 5. , 2.6, 5. , 2. , 2. , 1. ]),
 array([2. , 2.6, 7. ]),
 array([5., 6., 7., 3.]))

In [97]:
# otras formas de hacer indexing (usar una lista para hacer indexing)
v[[1,3,5,6]]

array([2., 5., 5., 6.])

In [101]:
#Indexacion usando tipos buleanos
v[[True , True , False, False, True, True, False, False, False]]

array([1. , 2. , 2.6, 5. ])

In [102]:
#Indexacion usando tipos buleanos
v > 4

array([False, False, False,  True, False,  True,  True,  True, False])

In [104]:
#Indexacion usando tipos buleanos
v[v > 4]

array([5., 5., 6., 7.])

In [105]:
print(v.shape) #atributo shape del arreglo de numpy
print(v.dtype) #atributo dtype
print(v.size) #atributo size
print(v.ndim) #atributo ndim

(9,)
float64
9
1


## 2D arrys

Como se menciono antes, es posible crear arreglos de mayor dimension. en este caso , veamos los arreglos 2D (tambien conocidos como matrices)

In [0]:
#creacion de un arreglo 2D (matriz) usando una lista de python
entradas = [
            [2,6,4,8,9],
            [2,6,7,9,2.3],
            [5,6,3.,4,2.,],
            [9,0,5,3,6,],
            [3.6,2.7,9.8,2,4] 
            ]

In [109]:
#creacion de un arreglo 2D (matriz) usando una lista de python
M = np.array(entradas)
M

array([[2. , 6. , 4. , 8. , 9. ],
       [2. , 6. , 7. , 9. , 2.3],
       [5. , 6. , 3. , 4. , 2. ],
       [9. , 0. , 5. , 3. , 6. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [110]:
#Indexacion en arreglos matriciales
M[0,0] , M[4,-1] , M[4,4]

(2.0, 4.0, 4.0)

In [115]:
#Slicing en arreglos matriciales
M[0:6:2, 0] 

array([2. , 5. , 3.6])

In [116]:
#Slicing en arreglos matriciales
M[0:6:2, 0:6:2] 

array([[2. , 4. , 9. ],
       [5. , 3. , 2. ],
       [3.6, 9.8, 4. ]])

In [117]:
#Slicing en arreglos matriciales
M[0:6:2, :] 

array([[2. , 6. , 4. , 8. , 9. ],
       [5. , 6. , 3. , 4. , 2. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [118]:
#Slicing en arreglos matriciales
M[0:, -1] 

array([9. , 2.3, 2. , 6. , 4. ])

In [121]:
#Slicing en arreglos matriciales
M[:, 0:-1:3] 

array([[2. , 8. ],
       [2. , 9. ],
       [5. , 4. ],
       [9. , 3. ],
       [3.6, 2. ]])

In [124]:
#Otras formas de indexing usando listas de python
M[:,[0,2,4]]

array([[2. , 4. , 9. ],
       [2. , 7. , 2.3],
       [5. , 3. , 2. ],
       [9. , 5. , 6. ],
       [3.6, 9.8, 4. ]])

In [137]:
#Otras formas de indexing
index = [[2,2],[0,0]], [[2,2],[0,0]]
M[index]

array([[3., 3.],
       [2., 2.]])

In [140]:
#Indexacion usando tipos buleanos
M > 5

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False, False]])

In [141]:
#Indexacion usando tipos buleanos
M[M > 5]

array([6. , 8. , 9. , 6. , 7. , 9. , 6. , 9. , 6. , 9.8])

In [142]:
print(M.shape) #atributo shape del arreglo de numpy
print(M.dtype) #atributo dtype
print(M.size) #atributo size
print(M.ndim) #atributo ndim

(5, 5)
float64
25
2


Numpy tiene muchas funciones para crear arreglos 

In [149]:
# Creación de un array de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [150]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [151]:
# Creación de un array de unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [152]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [158]:
# Creación de un array de una costante
np.full(5 , 3)

array([3, 3, 3, 3, 3])

In [160]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [163]:
# Creación de la matriz indentidad de 2x2.
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [165]:
# Crea un vector de cinco valores espaciados 
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [166]:
# Crea un vector de cinco valores espaciados
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [167]:
# Creación de un arreglo de valores aleatorios dados por una distribucion uniforme en el rango (0,1)
np.random.random(10)

array([0.04510897, 0.72451303, 0.44931964, 0.64594502, 0.96602371,
       0.23066903, 0.77233989, 0.37480168, 0.50343858, 0.43426386])

In [169]:
np.random.random((2,2))

array([[0.78446688, 0.28443774],
       [0.53767983, 0.14187252]])

In [171]:
# Creación arreglo de valores aleatorios dados por una distribucion normal 
np.random.normal(loc=0, scale=1, size=10)

array([ 0.45895605,  0.59282042,  0.59689481,  1.13078369, -1.11667261,
       -0.08581048,  2.08031318,  2.14934768, -0.39482094, -1.39840586])

In [172]:
np.random.normal(loc=0, scale=1, size=(3,3))

array([[-1.31358478,  1.00590217, -1.14564481],
       [ 0.24920212,  0.23690745, -0.51320557],
       [-0.64837712, -1.16955595,  1.02789509]])

In [175]:
# Creación de una arreglo de números enteros aleatorios dados por una distribucion uniforme en el rango dado
np.random.randint(low = 2, high=10, size=10)

array([7, 6, 4, 6, 8, 2, 8, 4, 9, 2])

In [176]:
np.random.randint(low = 2, high=10, size=(4,4))

array([[5, 3, 3, 7],
       [5, 3, 4, 2],
       [2, 9, 6, 7],
       [9, 2, 6, 5]])

## Ejercicios

1) Create a 3×3 numpy array of all True’s 

2) Replace all odd numbers in the below arry with -1 
```
Input

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


3) Convert a 1D array to a 2D array with 2 rows 



```
Input:

arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

ayuda: Investigar el metodo `reshape ` que tienen los arreglos de numpy


4) Stack arrays a and b vertically

```
Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

ayuda: investigar las funciones np.vstack , np.hstack 

5) Get the positions where elements of a and b match



```
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

ayuda: investigar la funcion np.where


6) Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)




```
arr = np.arange(9).reshape(3,3)
```



## Operaciones basicas entre entre arreglos del mismo tamaño

Las operaciones basicas entre arreglos se dan elemento a elemnto 

In [180]:
#definamos los dos arreglos
v = np.random.randint(low = 2, high=10, size=10)
w = np.random.randint(low = 2, high=10, size=10)
v,w

(array([2, 8, 5, 6, 7, 7, 2, 6, 8, 9]), array([9, 6, 5, 6, 7, 9, 5, 4, 3, 8]))

In [181]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v , w - v

(array([11, 14, 10, 12, 14, 16,  7, 10, 11, 17]),
 array([ 7, -2,  0,  0,  0,  2,  3, -2, -5, -1]))

In [182]:
#multiplicacion y division
w*v , w/v

(array([18, 48, 25, 36, 49, 63, 10, 24, 24, 72]),
 array([4.5       , 0.75      , 1.        , 1.        , 1.        ,
        1.28571429, 2.5       , 0.66666667, 0.375     , 0.88888889]))

In [183]:
#Potenciacion
w**v

array([       81,   1679616,      3125,     46656,    823543,   4782969,
              25,      4096,      6561, 134217728])

In [184]:
#definamos los dos arreglos 2D
v = np.random.randint(low = 2, high=10, size=(3,3))
w = np.random.randint(low = 2, high=10, size=(3,3))
v,w

(array([[8, 8, 6],
        [4, 8, 8],
        [3, 4, 2]]), array([[2, 9, 5],
        [8, 5, 6],
        [5, 2, 9]]))

In [188]:
#suma y resta de dos arreglos 1D de la misma longitud
w + v

array([[10, 17, 11],
       [12, 13, 14],
       [ 8,  6, 11]])

In [189]:
#multiplicacion y division
w*v 

array([[16, 72, 30],
       [32, 40, 48],
       [15,  8, 18]])

In [190]:
#Potenciacion
w**v

array([[     256, 43046721,    15625],
       [    4096,   390625,  1679616],
       [     125,       16,       81]])

## Operaciones basicas entre entre arreglos de diferente tamaño (Broadcasting)

In [0]:
#definamos un arreglo 1D con numeros aleatorios
v = np.random.randint(low = 2, high=10, size=10)

In [204]:
#suma y resta de un arreglo y una constante
v + 1 , v - 1

(array([ 4,  3, 10,  8,  8,  3,  3,  9,  7, 10]),
 array([2, 1, 8, 6, 6, 1, 1, 7, 5, 8]))

In [205]:
#multiplicacion  y division de un arreglo y una constante
v*2 , v/2

(array([ 6,  4, 18, 14, 14,  4,  4, 16, 12, 18]),
 array([1.5, 1. , 4.5, 3.5, 3.5, 1. , 1. , 4. , 3. , 4.5]))

In [206]:
#Comparaciones entre arreglo y una constante
v > 5

array([False, False,  True,  True,  True, False, False,  True,  True,
        True])

In [239]:
#Definamos dos arreglos con diferentes damaños
v = np.random.randint(low = 2, high=10, size=(4,4))
w = np.random.randint(low = 2, high=10, size=(1,4))
v

array([[2, 9, 3, 7],
       [8, 7, 3, 5],
       [9, 9, 9, 4],
       [7, 7, 7, 6]])

In [240]:
w

array([[2, 3, 3, 4]])

In [241]:
#Suma entre los dos arreglos
w + v

array([[ 4, 12,  6, 11],
       [10, 10,  6,  9],
       [11, 12, 12,  8],
       [ 9, 10, 10, 10]])

In [242]:
#Multiplicacion
w*v

array([[ 4, 27,  9, 28],
       [16, 21,  9, 20],
       [18, 27, 27, 16],
       [14, 21, 21, 24]])

In [243]:
#exponenciacion
w**v

array([[    4, 19683,    27, 16384],
       [  256,  2187,    27,  1024],
       [  512, 19683, 19683,   256],
       [  128,  2187,  2187,  4096]])

## Ufunctions 

algunos ejemplso de Ufunctions 


In [0]:
#definamos dos arreglos 1D con numeros aleatorios
v = np.random.random(10)

In [17]:
#sumar las componenetes de un arreglo
np.sum(v)

6.147133217665829

In [21]:
#funciones trigonometricas
np.sin(v)

array([0.47477787, 0.63835152, 0.01992436, 0.81485272, 0.63790557,
       0.41127137, 0.78796114, 0.55904736, 0.79741786, 0.43344421])

In [22]:
#exponencial
np.exp(v)

array([1.64002522, 1.99841579, 1.02012552, 2.59211741, 1.99725865,
       1.52782997, 2.47809627, 1.80983629, 2.51683941, 1.56566581])

In [23]:
#multiplicacion
np.multiply(v,v)

array([2.44739590e-01, 4.79355114e-01, 3.97032577e-04, 9.07208771e-01,
       4.78553430e-01, 1.79647475e-01, 8.23539248e-01, 3.51929419e-01,
       8.51936219e-01, 2.00982907e-01])

In [24]:
#media 
np.mean(v)

0.6147133217665829

In [25]:
#desviacion estandar 
np.std(v)

0.2719493565316493

## Ejercicios

Para los siguientes ejercicios concidere el suguiente conjunto de datos

In [0]:
#librearia que contiene el conjunto de tados llamados iris
from sklearn.datasets import load_iris

In [0]:
#utilizamos la funcion load_iris() para cargar los datos
dataset = load_iris()

In [5]:
#Inspecciones un poco los datos , tenga encuenta que los datos vienen en forma de diccionario
dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [0]:
#veamos la descripcion del data set
dataset['DESCR']

In [6]:
#veamos el nombre de las caracteristicas
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
#veamos las etiquetas
dataset['filename']

'/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/iris.csv'

In [0]:
#separemos los datos
X = dataset['data'][: , [0,1]]

1) Obtenga el valor maximo y el valor minimo de la matriz X, luego obtenga el valor maximo y minimo de cada una de las columnas (esto es cada una de las caracteristicas)

2) Obtenga el valor medio y la desviacion estandar para cada una de las caracteristicas

3) Para cada una de las caracteristica extraiga los valores que son mayores a sus medias

4) Una operacion muy frecuente cuando se trabaja con modelos de machinlearning es la estandarizacion de los datos (luego veremos esto a fonto) la cual esta definida por 

\begin{equation}
\frac{x-\mu}{s}
\end{equation}

$\mu$ es la media y s es la desviacion estandar.

cree una funcion que haga esta operacion sobre arreglos 1D de numpy y luego apliquela sobre cada una de las caracteristicas de nuestro datos