<a href="https://colab.research.google.com/github/darioblandon/Curso1/blob/main/S2/Taller_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/darioblandon/Curso1/blob/master/S2/clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplos



## Funciones

Una función es un bloque de código organizado y reutilizable que se utiliza para realizar una única acción relacionada. Las funciones proporcionan una mejor modularidad para su aplicación y un alto grado de reutilización de código.

In [ ]:
#Definimos una funcion que calcule la media de una lista de numeros
def media(v):
    media = 0
    for i in v:
        media += i

    return(media/len(v))

In [ ]:
#Definamos una funcion para calcular la varianza
def varianza(v):
    var = 0
    m = media(v)
    for i in v:
        var += (i - m)**2

    return(var/len(v))

In [ ]:
#Ejecutamos la funciones
lista = [4,2,2,2,2,3,4,5,6]
media(lista), varianza(lista)

(3.3333333333333335, 2.0)

Ejemplos de funciones ya construidas en python

In [ ]:
#Forma facil de calcular la media
sum(lista)/len(lista)

3.3333333333333335

In [ ]:
#Funcion que calcula el maximo y minimo
max(lista) , min(lista)

(6, 2)

# Librerias en python

Una libreria es una coleccion de clses y metodos los cuales nos permiten crear objetos sin la nececidad de programarlos explicitamente.

Existen muchas librerias, las mas utilizadas por nosostros seran:
* numpy
* pandas 
* matplotlib
* seaborn
* sklearn


## Numpy

Esta libreria proporciona objetos arreglos multidimensionales (tensores) de alto desempeño, ademas de erramientas para trabajar con estos arreglos

In [ ]:
#Importar numpy
import numpy as np

## 1D array 

un arreglo unidimensional es una colecion de tipos de datos los cuales se encuntran indexados ( tal y como las listas ). A diferencia de las listas, los arreglos 1D ( y en general los arreglos de cualquier dimension ) solo pueden contener un tipo de dato.

Los arreglos de python soportan indexacion y slicing

para crear un arreglo 1D de python , podemos usar una lista de numpy


In [ ]:
v = np.array([1,2,2,5,2.6,5,6,7,3]) #creacion de un arreglo 1D de numpy
print(type(v))
v #Veamos el vector y a que clase pertenece (esto es , veamos que tipo de dato es)

<class 'numpy.ndarray'>


array([1. , 2. , 2. , 5. , 2.6, 5. , 6. , 7. , 3. ])

In [ ]:
#indexacion
v[0], v[1] , v[-1] , v[8]

(1.0, 2.0, 3.0, 3.0)

In [ ]:
#slicing [indice_inicial:indice_fianl:paso]
v[0:5:2], v[::-1] , v[1::3] , v[5::]

(array([1. , 2. , 2.6]),
 array([3. , 7. , 6. , 5. , 2.6, 5. , 2. , 2. , 1. ]),
 array([2. , 2.6, 7. ]),
 array([5., 6., 7., 3.]))

In [ ]:
# otras formas de hacer indexing (usar una lista para hacer indexing)
v[[1,3,5,6]]

array([2., 5., 5., 6.])

In [ ]:
#Indexacion usando tipos buleanos
v[[True , True , False, False, True, True, False, False, False]]

array([1. , 2. , 2.6, 5. ])

In [ ]:
#Indexacion usando tipos buleanos
v > 4

array([False, False, False,  True, False,  True,  True,  True, False])

In [ ]:
#Indexacion usando tipos buleanos
v[v > 4]

array([5., 5., 6., 7.])

In [ ]:
print(v.shape) #atributo shape del arreglo de numpy
print(v.dtype) #atributo dtype
print(v.size) #atributo size
print(v.ndim) #atributo ndim

(9,)
float64
9
1


## 2D arrys

Como se menciono antes, es posible crear arreglos de mayor dimension. en este caso , veamos los arreglos 2D (tambien conocidos como matrices)

In [ ]:
#creacion de un arreglo 2D (matriz) usando una lista de python
entradas = [
            [2,6,4,8,9],
            [2,6,7,9,2.3],
            [5,6,3.,4,2.,],
            [9,0,5,3,6,],
            [3.6,2.7,9.8,2,4] 
            ]

In [ ]:
#creacion de un arreglo 2D (matriz) usando una lista de python
M = np.array(entradas)
M

array([[2. , 6. , 4. , 8. , 9. ],
       [2. , 6. , 7. , 9. , 2.3],
       [5. , 6. , 3. , 4. , 2. ],
       [9. , 0. , 5. , 3. , 6. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [ ]:
#Indexacion en arreglos matriciales
M[0,0] , M[4,-1] , M[4,4]

(2.0, 4.0, 4.0)

In [ ]:
#Slicing en arreglos matriciales
M[0:6:2, 0] 

array([2. , 5. , 3.6])

In [ ]:
#Slicing en arreglos matriciales
M[0:6:2, 0:6:2] 

array([[2. , 4. , 9. ],
       [5. , 3. , 2. ],
       [3.6, 9.8, 4. ]])

In [ ]:
#Slicing en arreglos matriciales
M[0:6:2, :] 

array([[2. , 6. , 4. , 8. , 9. ],
       [5. , 6. , 3. , 4. , 2. ],
       [3.6, 2.7, 9.8, 2. , 4. ]])

In [ ]:
#Slicing en arreglos matriciales
M[0:, -1] 

array([9. , 2.3, 2. , 6. , 4. ])

In [ ]:
#Slicing en arreglos matriciales
M[:, 0:-1:3] 

array([[2. , 8. ],
       [2. , 9. ],
       [5. , 4. ],
       [9. , 3. ],
       [3.6, 2. ]])

In [ ]:
#Otras formas de indexing usando listas de python
M[:,[0,2,4]]

array([[2. , 4. , 9. ],
       [2. , 7. , 2.3],
       [5. , 3. , 2. ],
       [9. , 5. , 6. ],
       [3.6, 9.8, 4. ]])

In [ ]:
#Otras formas de indexing
index = [[2,2],[0,0]], [[2,2],[0,0]]
M[index]

array([[3., 3.],
       [2., 2.]])

In [ ]:
#Indexacion usando tipos buleanos
M > 5

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False, False]])

In [ ]:
#Indexacion usando tipos buleanos
M[M > 5]

array([6. , 8. , 9. , 6. , 7. , 9. , 6. , 9. , 6. , 9.8])

In [ ]:
print(M.shape) #atributo shape del arreglo de numpy
print(M.dtype) #atributo dtype
print(M.size) #atributo size
print(M.ndim) #atributo ndim

(5, 5)
float64
25
2


Numpy tiene muchas funciones para crear arreglos 

In [ ]:
# Creación de un array de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# Creación de un array de unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creación de un array de una costante
np.full(5 , 3)

array([3, 3, 3, 3, 3])

In [ ]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
# Creación de la matriz indentidad de 2x2.
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Crea un vector de cinco valores espaciados 
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [ ]:
# Crea un vector de cinco valores espaciados
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [ ]:
# Creación de un arreglo de valores aleatorios dados por una distribucion uniforme en el rango (0,1)
np.random.random(10)

array([0.04510897, 0.72451303, 0.44931964, 0.64594502, 0.96602371,
       0.23066903, 0.77233989, 0.37480168, 0.50343858, 0.43426386])

In [ ]:
np.random.random((2,2))

array([[0.78446688, 0.28443774],
       [0.53767983, 0.14187252]])

In [ ]:
# Creación arreglo de valores aleatorios dados por una distribucion normal 
np.random.normal(loc=0, scale=1, size=10)

array([ 0.45895605,  0.59282042,  0.59689481,  1.13078369, -1.11667261,
       -0.08581048,  2.08031318,  2.14934768, -0.39482094, -1.39840586])

In [ ]:
np.random.normal(loc=0, scale=1, size=(3,3))

array([[-1.31358478,  1.00590217, -1.14564481],
       [ 0.24920212,  0.23690745, -0.51320557],
       [-0.64837712, -1.16955595,  1.02789509]])

In [ ]:
# Creación de una arreglo de números enteros aleatorios dados por una distribucion uniforme en el rango dado
np.random.randint(low = 2, high=10, size=10)

array([7, 6, 4, 6, 8, 2, 8, 4, 9, 2])

In [ ]:
np.random.randint(low = 2, high=10, size=(4,4))

array([[5, 3, 3, 7],
       [5, 3, 4, 2],
       [2, 9, 6, 7],
       [9, 2, 6, 5]])

## Ejercicios

1) Cree una matriz numpy de 3 × 3 de True

2) Reemplace todos los números impares en la siguiente matriz con -1
```
Input

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```


3) Convierta una matriz 1D en una matriz 2D con 2 filas



```
Input:

arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

ayuda: Investigar el metodo `reshape ` que tienen los arreglos de numpy


4) Apilar las matrices a y b verticalmente
```
Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

ayuda: investigar las funciones np.vstack , np.hstack 

5) Obtener las posiciones donde coinciden los elementos de a y b


```
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

ayuda: investigar la funcion np.where


6) Intercambiar las columnas 1 y 2 en la matriz arr.

arr = np.arange(9).reshape(3,3)




```
arr = np.arange(9).reshape(3,3)
```



7) grafique los siguientes datos 

    a) x = (1, 2, 3, 4),y = (2, 5, 4, 7)
    
    b) y= $x^2 * \exp(-x^2)$ , x = np.arange(0.0, 5.0, 0.01) (defina una funcion que devuelva f(x))

8) Cree una funcion que calcule dos numeros aleatorias a y b y de forma aleatoria realice una operacion entre ellos es decir (suma, resta, multiplicacion, division) y almacenelo en un diccionario.

9) Escribalos el diccionario del punto anterior en un archivo de texto mediante python.

10)Cargue los datos del archivo adjunto "expData.csv" (puede usar panda o nunpy), agrege una nueva columna que sea $ln(x)$, grafique ambas funciones con maplotlib y finalmente escriba la nueva columna en el archivo y cierrelo.